version: '3'

name: "secure-api"

services:

  postgres:
    image: postgres:alpine
    container_name: postgres_db
    environment:
      # Connection
      POSTGRES_USER: "postgres" # your_db_user 
      POSTGRES_PASSWORD: "123456" # your_db_password 
      POSTGRES_DB: "db-full-secure" # your_db_name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com" # your_email@example.com
      PGADMIN_DEFAULT_PASSWORD: "admin" # your_pgadmin_password
    ports:
      - "5051:80"
    depends_on:
      - postgres
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin/pgadmin4
    networks:
      - app-network

  server-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_boot_app
    depends_on:
      - postgres
      - pgadmin
    ports:
      - "8080:8080"
    environment:
      # must be the same as application.yml
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db-full-secure # cant be localhost because its a docker container
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_PROFILES_ACTIVE: prod # Activate the prod profile

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge