server:
  port: 9090

spring:
  # refers to database server or postgres user 
  datasource:
    username: postgres
    password: 123456

    url: jdbc:postgresql://localhost:5432/db-full-secure # pgAdmin4 python venv
    # url: jdbc:postgresql://silly.db.elephantsql.com:5432/tqcszcxm?user=tqcszcxm&password=SXgJrMstmZieuYMBUOLEdeAuY47wC1tC  # Elephant
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
    validateOnMigrate: false # You can set this to true during development to validate migrations
    schemas: public # The schema where your tables will be created
    table: flyway_schema_history # Table to store migration history
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect